name: Enviar Saludo
on: 
  workflow_dispatch

jobs:
  saludo:
   runs-on: ubuntu-lastest
   steps:
    - name : Mostrar saludo
      run: echo "hola"

    - name : Mostrar ubicacion
      run: pwd
      
     
